
project_id = "ssvskbejfacmjemphmry"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
password_min_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions]
enabled = true

[functions.submit-contact]
verify_jwt = false
