
# This file determines project configuration and behavior.

[functions]
  [functions.generate-outreach]
    verify_jwt = true
  [functions.send-influencer-email]
    verify_jwt = true
  [functions.send-influencer-dm]
    verify_jwt = true
