
# This file was created and managed by the Lovable AI assistant.
# Project ID should always stay as the first line
project_id = "ssvskbejfacmjemphmry"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[functions]
[functions.aria-ingest]
verify_jwt = false
[functions.reddit-scan]
verify_jwt = false
# Set up a cron job to run the Reddit scanner every hour
schedule = "0 * * * *"
[functions.rss-scraper]
verify_jwt = false
# Set up a cron job to run the RSS scraper every 2 hours
schedule = "0 */2 * * *"
[functions.aria-scraper]
verify_jwt = false
# Set up a cron job to run the YouTube RSS scraper daily at 8 AM UTC
schedule = "0 8 * * *"
[functions.slack-alert]
verify_jwt = false
[functions.executive-reports]
verify_jwt = false
