// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var BASE_URL = "https://www.ariaops.co.uk";
var SERVICES = [
  { name: "AI Reputation Management", path: "/ai-reputation-management", description: "Manage how AI models and LLMs represent a person or brand." },
  { name: "Online Reputation Management (UK)", path: "/online-reputation-management-uk", description: "Full-service UK online reputation management." },
  { name: "Suppress Negative Google Results", path: "/suppress-negative-google-results", description: "Push down and suppress damaging Google search results." },
  { name: "Negative Search Result Suppression", path: "/negative-search-result-suppression", description: "Systematic suppression of negative search results." },
  { name: "Generative Engine Optimisation", path: "/generative-engine-optimisation", description: "Optimise visibility across generative AI search engines." },
  { name: "AI Search Visibility", path: "/ai-search-visibility", description: "Improve how entities appear in AI-powered search." },
  { name: "LLM Reputation Management", path: "/llm-reputation-management", description: "Correct and shape LLM outputs about an entity." },
  { name: "Executive Reputation Protection", path: "/executive-reputation-protection", description: "Reputation protection for senior executives." },
  { name: "Founder Reputation Protection", path: "/founder-reputation-protection", description: "Reputation protection for founders and entrepreneurs." },
  { name: "Athlete Reputation Management", path: "/athlete-reputation-management", description: "Reputation management for professional athletes." },
  { name: "Crisis Reputation Management", path: "/crisis-reputation-management", description: "Crisis PR and reputation response during active incidents." },
  { name: "Crisis Communications", path: "/crisis-communications", description: "Crisis communications strategy and execution." },
  { name: "Corporate Reputation Management", path: "/corporate-reputation-management", description: "Reputation management for companies and brands." },
  { name: "Personal Reputation Management", path: "/personal-reputation-management", description: "Reputation management for private individuals." },
  { name: "Online Reputation Repair", path: "/online-reputation-repair", description: "Repair damaged online reputations." },
  { name: "Legal Defence & Compliance", path: "/legal-defence-compliance", description: "Legal-led reputation defence and compliance support." },
  { name: "Remove Google Reviews", path: "/services/remove-google-reviews", description: "Remove fake or defamatory Google reviews." },
  { name: "Online Impersonation (UK)", path: "/services/online-impersonation-uk", description: "Tackle online impersonation and fake profiles." },
  { name: "Brand Protection", path: "/services/brand-protection", description: "Protect brand assets and identity online." },
  { name: "Legal Shield", path: "/services/legal-shield", description: "Legal escalation workflow for reputation threats." }
];
var list_services_default = defineTool({
  name: "list_reputation_services",
  title: "List reputation services",
  description: "List the reputation management and crisis PR services offered by A.R.I.A / ariaops.co.uk, with a short description and a URL for each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const services = SERVICES.map((s) => ({ ...s, url: `${BASE_URL}${s.path}` }));
    const text = services.map((s) => `- ${s.name}: ${s.description} (${s.url})`).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { services }
    };
  }
});

// src/lib/mcp/tools/estimate-threat-score.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var BASE_URL2 = "https://www.ariaops.co.uk";
function scoreForName(name) {
  const normalized = name.trim().toLowerCase();
  let hash = 0;
  for (let i = 0; i < normalized.length; i++) {
    hash = (hash * 31 + normalized.charCodeAt(i)) % 1e5;
  }
  return 22 + hash % 67;
}
function band(score) {
  if (score >= 70) return { level: "High", summary: "Significant reputation exposure detected; proactive defence recommended." };
  if (score >= 45) return { level: "Moderate", summary: "Some reputation risk indicators present; monitoring advised." };
  return { level: "Low", summary: "Limited reputation risk indicators at this time." };
}
var estimate_threat_score_default = defineTool2({
  name: "estimate_reputation_threat_score",
  title: "Estimate reputation threat score",
  description: "Return an illustrative reputation threat score (0-100) and risk band for a given person or brand name. This is a simulated estimate matching the public lead-magnet tool, not a live OSINT scan.",
  inputSchema: {
    entity_name: z.string().min(1).describe("The person or brand name to estimate a reputation threat score for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ entity_name }) => {
    const score = scoreForName(entity_name);
    const { level, summary } = band(score);
    const text = `Reputation threat score for "${entity_name}": ${score}/100 (${level} risk). ${summary} Request a full scan at ${BASE_URL2}/scan.`;
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        entity_name,
        score,
        level,
        summary,
        scan_url: `${BASE_URL2}/scan`,
        note: "Simulated estimate for guidance only; not a live intelligence scan."
      }
    };
  }
});

// src/lib/mcp/tools/search-blog.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.49.4";
import { z as z2 } from "npm:zod@^3.25.76";
var BASE_URL3 = "https://www.ariaops.co.uk";
function getSupabase() {
  const url = process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY ?? process.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) {
    throw new Error("Supabase URL / publishable key not configured");
  }
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_blog_default = defineTool3({
  name: "search_blog_posts",
  title: "Search blog & insights",
  description: "Search the A.R.I.A / ariaops.co.uk published blog and insights articles about reputation management, crisis PR and AI search visibility. Returns matching article titles, summaries and URLs.",
  inputSchema: {
    query: z2.string().min(1).describe("Keywords to search article titles and summaries for."),
    limit: z2.number().int().min(1).max(20).optional().describe("Max results to return (default 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const max = limit ?? 5;
    try {
      const supabase = getSupabase();
      const { data, error } = await supabase.from("blog_posts").select("title, slug, summary, canonical_url, published_at").or(`title.ilike.%${query}%,summary.ilike.%${query}%`).order("published_at", { ascending: false }).limit(max);
      if (error) {
        return { content: [{ type: "text", text: `Search failed: ${error.message}` }], isError: true };
      }
      const results = (data ?? []).map((p) => ({
        title: p.title,
        summary: p.summary,
        url: p.canonical_url || `${BASE_URL3}/blog/${p.slug}`,
        published_at: p.published_at
      }));
      if (results.length === 0) {
        return { content: [{ type: "text", text: `No articles found for "${query}".` }] };
      }
      const text = results.map((r) => `- ${r.title}: ${r.summary ?? ""} (${r.url})`).join("\n");
      return { content: [{ type: "text", text }], structuredContent: { results } };
    } catch (e) {
      return {
        content: [{ type: "text", text: e instanceof Error ? e.message : "Unknown error" }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "nphqcwigrxcguztkscak";
var mcp_default = defineMcp({
  name: "ariaops-mcp",
  title: "A.R.I.A Reputation Intelligence MCP",
  version: "0.1.0",
  instructions: "Tools for A.R.I.A (ariaops.co.uk), a reputation intelligence and crisis PR platform. Use `list_reputation_services` to see available services, `estimate_reputation_threat_score` for an illustrative risk estimate for a name, and `search_blog_posts` to find published insight articles.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, estimate_threat_score_default, search_blog_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
