// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssvskbejfacmjemphmry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzdnNrYmVqZmFjbWplbXBobXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Njc2NDksImV4cCI6MjA2MzI0MzY0OX0._UVl3ImgN-opAhne5FItzGXlLq41BqJmfAdqZO3vZXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);