// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://nphqcwigrxcguztkscak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5waHFjd2lncnhjZ3V6dGtzY2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NTEzOTksImV4cCI6MjA4ODMyNzM5OX0.3Dz8zvUOybcnLXyPJ6t9jzk1gdFa9V-tJQS9hLd6d04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);